name: Cancel

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cancel:
    name: Cancel
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Cancel running heavy workflows
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          workflow_id: .github/workflows/coverage.yml,.github/workflows/e2e.yml
          access_token: ${{ github.token }}
