name: Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  coverage:
    name: Coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install, build and prepare fixtures
        run: |
          yarn
          yarn fixtures:install
      - name: Test with coverage enabled
        run: yarn coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage
          token: ${{ secrets.CODECOV_TOKEN }}
