name: E2E - Perf Measure

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  main:
    name: Main
    uses: ./.github/workflows/e2e.yml
    with:
      test_dirs: e2e/perf-measure
