name: E2E - Realworld Use

on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release

jobs:
  main:
    name: Main
    uses: ./.github/workflows/e2e.yml
    with:
      target_dirs: e2e/realworld-use
