name: E2E - Feasibility Check

on:
  push:
    branches:
      - master
      - publish
  pull_request:
    branches:
      - master
      - publish

jobs:
  main:
    name: Main
    uses: ./.github/workflows/e2e.yml
    with:
      target_dirs: e2e/feasibility-check
