name: E2E

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  e2e:
    name: E2E
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      TEST_DIRS: e2e/feasibility-check e2e/perf-measure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install, build and prepare fixtures
        run: |
          yarn
          yarn fixtures install ${{ env.TEST_DIRS }}
      - name: Test end to end cases
        run: yarn e2e ${{ env.TEST_DIRS }}
