name: E2E

on:
  workflow_call:
    inputs:
      target_dirs:
        required: true
        type: string

jobs:
  cancel-prev:
    name: Cancel Prev
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: Cancel Prev
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  main:
    name: Main
    needs: cancel-prev
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install, build and prepare fixtures
        run: |
          yarn
          yarn fixtures install ${{ inputs.target_dirs }}
      - name: Test end to end cases
        run: yarn e2e ${{ inputs.target_dirs }}
