name: Verify and Publish

on:
  push:
    branches:
      - master
      - release

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  publish:
    name: Publish
    needs:
      - test
      - lint
    runs-on: ubuntu-20.04
    env:
      NPM_REGISTRY_URL: https://registry.npmjs.org
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_AUTOMATION }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: ${{ env.NPM_REGISTRY_URL }}
      - name: Install and build
        run: yarn
      - name: Publish
        run: |
          git config user.name "uno"
          git config user.email "licg9999@126.com"
          yarn autopublish
        env:
          GH_TOKEN: ${{ secrets.GH_AUTOMATION }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
